- add little/big endian test to the configure script - on disk vector/matrix read/write use now little endian convention wheter the architecture use little or big endian byte ordering
git-svn-id: https://www.nick-ux.org/diagham/svn/trunk@183 b9410c57-6ef9-0310-98bc-a73ba792996a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4479,6 +4479,67 @@ echo "$as_me: error: MPI C++ compiler (${MPI_CXX}) not found." >&2;}
 fi
 
 
+
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int main()
+{
+	short s = 1;
+	short* ptr = &s;
+	unsigned char c = *((char*)ptr);
+	return c;
+}
+
+
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BIGENDIAN
+_ACEOF
+
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LITTLEENDIAN
+_ACEOF
+
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+
 CXXFLAGS="-O2 -g -Wall "
 INCLUDES="-I\$(top_srcdir)/src"
 
